"""
Standalone debug script to create a Google Calendar event with a Meet link.

Usage:
    python debug_google_calendar_event.py

It reads google_token.json (generated by create_google_token.py), attempts to create
an event on the configured calendar, and prints the resulting Meet link or detailed
error information from the Google API.
"""

from __future__ import annotations

import datetime as dt
import os
import sys
import uuid
from pathlib import Path

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

SCOPES = [
    "https://www.googleapis.com/auth/calendar",
    "https://www.googleapis.com/auth/calendar.events",
]
_REPO = Path(__file__).resolve().parent.parent.parent
_DATA = _REPO / "app" / "data"
CREDENTIALS_PATH = str(_DATA / "google_credentials.json")
TOKEN_PATH = str(_DATA / "google_token.json")
DEFAULT_TZ = "Africa/Casablanca"
TEST_CALENDAR_ID = os.getenv("PROMIND7_GOOGLE_CALENDAR_ID", "primary")


def _choose_timezone() -> str:
    return os.getenv("TZ") or DEFAULT_TZ


def load_credentials() -> Credentials:
    if not os.path.exists(TOKEN_PATH):
        print(f"ERROR: {TOKEN_PATH} not found. Run create_google_token.py first.")
        sys.exit(1)
    try:
        creds = Credentials.from_authorized_user_file(TOKEN_PATH, SCOPES)
    except Exception as exc:  # noqa: BLE001
        print(f"ERROR: failed to read {TOKEN_PATH}: {exc}")
        sys.exit(1)

    if not creds.valid:
        if creds.refresh_token:
            print("Refreshing access token...")
            try:
                creds.refresh(Request())
                with open(TOKEN_PATH, "w", encoding="utf-8") as f:
                    f.write(creds.to_json())
            except Exception as exc:  # noqa: BLE001
                print(f"ERROR: token refresh failed: {exc}")
                sys.exit(1)
        else:
            print("ERROR: token invalid and has no refresh_token. Regenerate it.")
            sys.exit(1)
    return creds


def _extract_meet_url(event: dict) -> str:
    if not event:
        return ""
    if event.get("hangoutLink"):
        return event["hangoutLink"]
    conference = event.get("conferenceData") or {}
    for ep in conference.get("entryPoints", []) or []:
        if ep.get("entryPointType") and ep.get("entryPointType").lower() != "video":
            continue
        if ep.get("uri"):
            return ep["uri"]
    return ""


def main() -> None:
    try:
        creds = load_credentials()
        service = build("calendar", "v3", credentials=creds)

        now = dt.datetime.utcnow()
        start = now + dt.timedelta(minutes=10)
        end = start + dt.timedelta(minutes=30)
        tz = _choose_timezone()

        event_body = {
            "summary": "ProMind7 test event",
            "description": "Debug event created from debug_google_calendar_event.py",
            "start": {
                "dateTime": start.isoformat(),
                "timeZone": tz,
            },
            "end": {
                "dateTime": end.isoformat(),
                "timeZone": tz,
            },
            "conferenceData": {
                "createRequest": {
                    "conferenceSolutionKey": {"type": "hangoutsMeet"},
                    "requestId": str(uuid.uuid4()),
                }
            },
        }

        print(f"Creating test event in calendar '{TEST_CALENDAR_ID}'...")
        event = (
            service.events()
            .insert(
                calendarId=TEST_CALENDAR_ID,
                body=event_body,
                conferenceDataVersion=1,
            )
            .execute()
        )

        meet_url = _extract_meet_url(event)
        print("Event created successfully:")
        print(f"  id: {event.get('id')}")
        print(f"  htmlLink: {event.get('htmlLink')}")
        print(f"  meet_url: {meet_url or '(none)'}")

    except HttpError as http_exc:  # type: ignore
        status = getattr(http_exc, "resp", None)
        status_code = getattr(status, "status", "?")
        print("ERROR while creating Google Calendar event (HttpError):")
        print(f"  status: {status_code}")
        print(f"  reason: {getattr(http_exc, 'reason', '')}")
        try:
            print(f"  body: {http_exc.error_details}")
        except Exception:  # noqa: BLE001
            print(f"  body: {getattr(http_exc, 'content', '')}")
        sys.exit(1)
    except Exception as exc:  # noqa: BLE001
        print("ERROR while creating Google Calendar event:")
        print(repr(exc))
        sys.exit(1)


if __name__ == "__main__":
    main()
